### ISSUE TITLE
Error in reproducing Curve_fit_widget_1.ipynb

### ISSUE THREAD

**Issue by animesh** [tirthajyoti/Widgets#1]
Demo sounds really cool @tirthajyoti , thanks a tonne for sharing :+1:  However there is error 

````
/usr/local/lib/python3.4/dist-packages/scipy/optimize/minpack.py:785: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
````

which probably has nothing to do with your code and just my lack of understanding of curve fitting? sharing none the less...

**Comment by tirthajyoti** [comment]
Animesh,

Another local user here in Bay area directly contacted me about the same issue. He also solved it on his own.

The program runs for me in 3.6 but not 2.7.

kwargs.values()
In Python 3.6 and above, you'll receive the key-value pairs in order, but in earlier versions, the pairs will be output in a random order.

**Comment by animesh** [comment]
Thanks for the tip @tirthajyoti , will try again with some other env :+1:
